"use client";

import { CheckCircle2, Clipboard, LoaderCircle, TriangleAlert } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Button, buttonVariants } from "@/components/ui/button";
import { EDGE_FUNCTIONS } from "@/config/edge-functions";
import { ROUTES } from "@/config/routes";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import type { CreateRestaurantAdminResponse, CreateRestaurantResponse } from "@/types/edge-functions";
import { buildAdminPayload, buildRestaurantPayload, EMPTY_DRAFT, getFunctionErrorMessage, validateNewRestaurantDraft, type NewRestaurantDraft, type NewRestaurantErrors } from "./new-restaurant-data";

type FlowStatus = "initial" | "saving_restaurant" | "creating_admin" | "success" | "partial" | "error";
type CreatedRestaurant = Pick<CreateRestaurantResponse, "restaurant_id" | "branch_id" | "qr_url" | "token_last4">;

export function NewRestaurantClient() {
  const supabase = useMemo(() => getSupabaseBrowserClient(), []);
  const [draft, setDraft] = useState<NewRestaurantDraft>(EMPTY_DRAFT);
  const [errors, setErrors] = useState<NewRestaurantErrors>({});
  const [status, setStatus] = useState<FlowStatus>("initial");
  const [message, setMessage] = useState<string | null>(null);
  const [created, setCreated] = useState<CreatedRestaurant | null>(null);
  const busy = status === "saving_restaurant" || status === "creating_admin";

  function update<K extends keyof NewRestaurantDraft>(key: K, value: NewRestaurantDraft[K]) { setDraft((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: undefined })); }
  async function invoke<T>(name: typeof EDGE_FUNCTIONS.CREATE_RESTAURANT | typeof EDGE_FUNCTIONS.CREATE_RESTAURANT_ADMIN, body: Record<string, unknown>, scope: "restaurant" | "admin"): Promise<T> { const { data, error } = await supabase.functions.invoke<T>(name, { body }); if (error || !data) { const code = await readErrorCode(error); throw new Error(getFunctionErrorMessage(scope, code)); } return data; }
  async function createAdmin(restaurant: CreatedRestaurant) { setStatus("creating_admin"); setMessage(null); try { await invoke<CreateRestaurantAdminResponse>(EDGE_FUNCTIONS.CREATE_RESTAURANT_ADMIN, buildAdminPayload(draft, restaurant.restaurant_id), "admin"); setStatus("success"); } catch (error) { setMessage(error instanceof Error ? error.message : getFunctionErrorMessage("admin", "server_error")); setStatus("partial"); } }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (busy || created) return; const nextErrors = validateNewRestaurantDraft(draft); setErrors(nextErrors); if (Object.keys(nextErrors).length) { setStatus("error"); setMessage("Revisa los campos marcados antes de continuar."); return; } setStatus("saving_restaurant"); setMessage(null); try { const restaurant = await invoke<CreateRestaurantResponse>(EDGE_FUNCTIONS.CREATE_RESTAURANT, buildRestaurantPayload(draft), "restaurant"); const result = { restaurant_id: restaurant.restaurant_id, branch_id: restaurant.branch_id, qr_url: restaurant.qr_url, token_last4: restaurant.token_last4 }; setCreated(result); await createAdmin(result); } catch (error) { setMessage(error instanceof Error ? error.message : getFunctionErrorMessage("restaurant", "server_error")); setStatus("error"); } }
  function reset() { setDraft(EMPTY_DRAFT); setErrors({}); setStatus("initial"); setMessage(null); setCreated(null); }

  return <div className="mx-auto max-w-5xl space-y-8"><div><p className="text-sm font-medium text-slate-500">Restaurantes</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Nuevo restaurante cliente</h2><p className="mt-2 max-w-2xl text-sm text-slate-600">Crea el restaurante, su primera sucursal y el primer administrador en un solo flujo.</p></div>
    {status === "success" || status === "partial" ? <Result status={status} message={message} created={created!} onRetry={() => void createAdmin(created!)} onReset={reset} /> : <form onSubmit={submit} noValidate className="space-y-10">
      {message ? <div role="alert" className="flex gap-3 border-l-2 border-red-600 bg-red-50 px-4 py-3 text-sm text-red-800"><TriangleAlert className="mt-0.5 size-4 shrink-0" />{message}</div> : null}
      <Section number="1" title="Restaurante" description="Datos comerciales y de contacto."><Grid><Field label="Nombre del restaurante" required error={errors.restaurantName}><Input value={draft.restaurantName} onChange={(v) => update("restaurantName", v)} disabled={busy} /></Field><Field label="Razon social"><Input value={draft.legalName} onChange={(v) => update("legalName", v)} disabled={busy} /></Field><Field label="Contacto"><Input value={draft.contactName} onChange={(v) => update("contactName", v)} disabled={busy} /></Field><Field label="Email de contacto" error={errors.contactEmail}><Input type="email" value={draft.contactEmail} onChange={(v) => update("contactEmail", v)} disabled={busy} /></Field><Field label="Telefono" error={errors.contactPhone}><Input type="tel" value={draft.contactPhone} onChange={(v) => update("contactPhone", v)} disabled={busy} /></Field></Grid></Section>
      <Section number="2" title="Cuenta y plan" description="Configuracion inicial de la cuenta."><Grid><Field label="Plan" required><Select value={draft.planCode} onChange={(v) => update("planCode", v as NewRestaurantDraft["planCode"])} disabled={busy} options={["demo", "basico", "pro", "custom"]} /></Field><Field label="Estado de cuenta" required><Select value={draft.accountStatus} onChange={(v) => update("accountStatus", v as NewRestaurantDraft["accountStatus"])} disabled={busy} options={["demo", "pilot", "active"]} /></Field></Grid><label className="mt-5 flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" checked={draft.createInitialQr} onChange={(e) => update("createInitialQr", e.target.checked)} disabled={busy} className="size-4" />Generar QR inicial</label></Section>
      <Section number="3" title="Primera sucursal" description="La ubicacion inicial del restaurante."><Grid><Field label="Nombre de sucursal" required error={errors.branchName}><Input value={draft.branchName} onChange={(v) => update("branchName", v)} disabled={busy} /></Field><Field label="Slug"><Input value={draft.branchSlug} onChange={(v) => update("branchSlug", v)} disabled={busy} /></Field><Field label="Direccion"><Input value={draft.branchAddress} onChange={(v) => update("branchAddress", v)} disabled={busy} /></Field><Field label="Telefono interno" error={errors.branchInternalPhone}><Input type="tel" value={draft.branchInternalPhone} onChange={(v) => update("branchInternalPhone", v)} disabled={busy} /></Field><Field label="Notas" wide><textarea value={draft.branchNotes} onChange={(e) => update("branchNotes", e.target.value)} disabled={busy} rows={3} className={inputClass} /></Field></Grid></Section>
      <Section number="4" title="Primer administrador" description="Recibira acceso para administrar el restaurante."><Grid><Field label="Nombre completo" required error={errors.adminFullName}><Input value={draft.adminFullName} onChange={(v) => update("adminFullName", v)} disabled={busy} /></Field><Field label="Email" required error={errors.adminEmail}><Input type="email" value={draft.adminEmail} onChange={(v) => update("adminEmail", v)} disabled={busy} /></Field></Grid></Section>
      <div className="flex flex-col-reverse gap-3 border-t border-slate-200 pt-6 sm:flex-row sm:justify-end"><Link className={buttonVariants({ variant: "outline" })} href={ROUTES.PLATFORM_ADMIN_RESTAURANTS}>Volver a restaurantes</Link><Button type="submit" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" /> : null}{status === "saving_restaurant" ? "Guardando restaurante..." : status === "creating_admin" ? "Creando administrador..." : "Crear restaurante"}</Button></div>
    </form>}
  </div>;
}

function Result({ status, message, created, onRetry, onReset }: { status: "success" | "partial"; message: string | null; created: CreatedRestaurant; onRetry: () => void; onReset: () => void }) { const success = status === "success"; return <div className="space-y-6 border-t border-slate-200 pt-8"><div className="flex gap-4"><div className={`grid size-10 shrink-0 place-items-center rounded-full ${success ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>{success ? <CheckCircle2 className="size-5" /> : <TriangleAlert className="size-5" />}</div><div><h3 className="text-xl font-semibold">{success ? "Restaurante creado correctamente" : "Restaurante creado; administrador pendiente"}</h3><p className="mt-2 text-sm text-slate-600">Sucursal inicial creada.</p><p className="text-sm text-slate-600">{success ? "Administrador invitado o creado." : message}</p></div></div>{created.qr_url ? <div className="border-l-2 border-slate-300 pl-4"><p className="text-sm font-medium">URL QR generada</p><p className="mt-1 break-all text-sm text-slate-600">{created.qr_url}</p>{created.token_last4 ? <p className="mt-1 text-xs text-slate-500">Ultimos 4 caracteres: {created.token_last4}</p> : null}<Button type="button" variant="outline" className="mt-3" onClick={() => void navigator.clipboard.writeText(created.qr_url!)}><Clipboard />Copiar QR</Button></div> : null}<div className="flex flex-wrap gap-3">{!success ? <Button type="button" onClick={onRetry}>Reintentar administrador</Button> : null}<Button type="button" variant={success ? "default" : "outline"} onClick={onReset}>Crear otro restaurante</Button><Link className={buttonVariants({ variant: "outline" })} href={ROUTES.PLATFORM_ADMIN_RESTAURANTS}>Volver a restaurantes</Link></div></div>; }
function Section({ number, title, description, children }: { number: string; title: string; description: string; children: React.ReactNode }) { return <section className="grid gap-5 border-t border-slate-200 pt-6 md:grid-cols-[220px_1fr]"><div><p className="text-xs font-semibold text-slate-400">{number.padStart(2, "0")}</p><h3 className="mt-1 font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div><div>{children}</div></section>; }
function Grid({ children }: { children: React.ReactNode }) { return <div className="grid gap-5 sm:grid-cols-2">{children}</div>; }
function Field({ label, required, error, wide, children }: { label: string; required?: boolean; error?: string; wide?: boolean; children: React.ReactNode }) { return <label className={`block space-y-2 text-sm font-medium text-slate-700 ${wide ? "sm:col-span-2" : ""}`}><span>{label}{required ? " *" : ""}</span>{children}{error ? <span className="block text-xs font-medium text-red-700">{error}</span> : null}</label>; }
const inputClass = "w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm outline-none transition focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10 disabled:bg-slate-100";
function Input({ value, onChange, disabled, type = "text" }: { value: string; onChange: (value: string) => void; disabled: boolean; type?: string }) { return <input type={type} value={value} onChange={(e) => onChange(e.target.value)} disabled={disabled} className={inputClass} />; }
function Select({ value, onChange, disabled, options }: { value: string; onChange: (value: string) => void; disabled: boolean; options: string[] }) { return <select value={value} onChange={(e) => onChange(e.target.value)} disabled={disabled} className={inputClass}>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select>; }
async function readErrorCode(error: unknown) { const context = (error as { context?: { json?: () => Promise<unknown> } })?.context; if (!context?.json) return "server_error"; try { const body = await context.json() as { error?: { code?: string } }; return body.error?.code ?? "server_error"; } catch { return "server_error"; } }
