export const ROUTES = {
  HOME: "/",
  PRIVACY: "/privacidad",
  LOGIN: "/login",
  AUTH_CALLBACK: "/auth/callback",
  LOGOUT: "/logout",
  SURVEY_QR: "/s",
  DEVICE_SURVEY: "/d",
  THANK_YOU: "/gracias",
  INVALID_LINK: "/enlace-invalido",
  APP: "/app",
  PLATFORM_ADMIN: "/platform-admin",
  APP_DASHBOARD: "/app/dashboard",
  APP_RESPONSES: "/app/respuestas",
  APP_RESPONSE_DETAIL: "/app/respuestas/detalle",
  APP_ALERTS: "/app/alertas",
  APP_ALERT_DETAIL: "/app/alertas/detalle",
  APP_EXPORT: "/app/exportar",
  APP_SETTINGS: "/app/configuracion",
  APP_SETTINGS_ACCOUNT: "/app/configuracion/cuenta",
  APP_SETTINGS_WAITERS: "/app/configuracion/meseros",
  APP_SETTINGS_QR: "/app/configuracion/qr",
  APP_SETTINGS_DEVICES: "/app/configuracion/dispositivos",
  APP_SETTINGS_QUESTIONS: "/app/configuracion/preguntas",
  APP_SETTINGS_USERS: "/app/configuracion/usuarios",
  APP_SETTINGS_ZONES: "/app/configuracion/zonas",
  APP_SETTINGS_BRANCHES: "/app/configuracion/sucursales",
  APP_NO_ACCESS: "/app/sin-acceso",
  PLATFORM_ADMIN_RESTAURANTS: "/platform-admin/restaurantes",
  PLATFORM_ADMIN_RESTAURANT_NEW: "/platform-admin/restaurantes/nuevo",
  PLATFORM_ADMIN_RESTAURANT_DETAIL: "/platform-admin/restaurantes/detalle",
  PLATFORM_ADMIN_NO_ACCESS: "/platform-admin/sin-acceso",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
